---
title: "Retrieving US Census Bureau Data (Population Dataset) "
output: html_document
date: "2024-01-16"
---

```{r setup, include=FALSE}
# Install and load required packages
install.packages(c("tidycensus", "tidyverse"))
install.packages("sf")

library(tidycensus)
library(tidyverse)
library(dplyr)
library(sf)

# Tigris package used to retrieve the corresponding geographic dataset from the US Census Bureau and pre-merge it with the tabular data obtained from the Census API below
options(tigris_use_cache = TRUE)
```

```{r}
# Set Census API Key, retrieve your own from online and input below
census_api_key("...", install = TRUE)
```

```{r}
# Retrieve data from 2020 Decennial Census on total population of county subdivisions in VT. Contains geographic data through geometry setting below:
pop20 <- get_decennial(
  geography = "county subdivision",
  state = "50",
  variables = "P1_001N",
  geometry = TRUE,
  year = 2020
)

# Use to view Census and ACS 5-year variables

census_vars <- load_variables(2020, "pl")

acs_vars <- load_variables(2022, "acs5")

# Establish list of variables necessary to pull total population over 65. Includes age groups 65 and older for both males and females, the groups are as follows: 65 and 66, 67 to 69, 70 to 74, 75 to 79, 80 to 84, 84 and over. Variables were found using the acs_vars df above. 

vars_of_interest <- c("B01001_020","B01001_021","B01001_022","B01001_023","B01001_024","B01001_025","B01001_044", "B01001_045", "B01001_046", "B01001_047", "B01001_048", "B01001_049")

# Retrieve data from the ACS 5-year for the above age groups 
age20 <- get_acs(
  geography = "county subdivision",
  state = "50",
  variables = vars_of_interest,
  survey = "acs5",
  year = 2022
)

# Create dataframe that creates a column for total number of people 65 and over (elderly) for each town GEOID
elderly_bytown <- age20%>%
  group_by(GEOID)%>%
  summarize(elderly_pop = sum(estimate))

# Join the total population dataset with the age dataset, create a column for % elderly, and modify the GEOID to include the state, county, and town FIPS codes so they can be joined to other population data in later analysis. Clean and reorder data. Change CRS to VT state plane EPSG 6589.
total_population_data <- pop20%>%
  inner_join(elderly_bytown, by = "GEOID")%>%
  rename(total_pop = value,
         subdivision_name = NAME)%>%
  mutate( pct_elderly = ((elderly_pop / total_pop)*100))%>%
  separate(GEOID, into = c("fips_state", "fips_county","fips_subdivision"), sep = c(2,5), remove = FALSE)%>%
  relocate(geometry, .after = pct_elderly)%>%
  select(!variable)%>%
  st_transform(geometry, crs = st_crs(6589))


```

```{r}
# Export Data
setwd("~/Desktop")
write_csv(census_vars, "tidycensus_variables.csv")
write_csv(acs_vars, "tidyacs_variables.csv")
write_csv(total_population_data, "tidycensus_alldata.csv")
```

